### ISSUE TITLE
Why save is needed ?

### ISSUE THREAD

**Issue by lllopo** [animus-coop/vscode-phpstorm-formatter#1]
Why do we need to save the file before formatting ? Many other formatting extensions also use external formatters, but as far as i know - they grab the file content, create a tmp file, run it through the external formatter and then inject the result back. Just check some of them and do the same.

**Comment by manuvalle** [comment]
@lllopo I didn't think about it, that might be a possible solution. I will give it a try in the following days. Thanks!

**Comment by manuvalle** [comment]
@lllopo I've added this feature and pushed the latest changes to the [develop branch](https://github.com/animus-coop/vscode-phpstorm-formatter/tree/develop).

I will do some more testing and will publish the update soon.

Thanks for the suggestion!
