### ISSUE TITLE
Error VSCODE

### ISSUE THREAD

**Issue by esjdev** [animus-coop/vscode-phpstorm-formatter#11]
PHPStorm Formatter: Failed to format the document

**Comment by soymanuvalle** [comment]
Hi @esjdev, can you send more data about your environment please?

What OS do you have? Could you send a screenshot or wirte down how the settings of the extension looks like on your vscode?

**Comment by esjdev** [comment]
> Oi @esjdev , você pode enviar mais dados sobre o seu ambiente, por favor?
> 
> Qual sistema operacional você possui? Você poderia enviar uma captura de tela ou ver como as configurações da extensão se parecem no seu vscode?

Use Windows 10.

https://i.imgur.com/rWlv0Xw.png

**Comment by esjdev** [comment]
I gave up using it. I'm using another :D

closed
