### ISSUE TITLE
[QUESTION] Does this plugin work on macOS?

### ISSUE THREAD

**Issue by cristiangervasi** [animus-coop/vscode-phpstorm-formatter#3]
Hi, i tried it on macOS with a fresh installation of PHPStorm, i have wrote the path to the bin folder of /Applications/PHPStorm/.../bin path but it doesn't work. On Windows 10 is working correctly without filling the style guide field, do i need to fill it on macOS? What is the correct "bin" path on macOS?

**Comment by manuvalle** [comment]
Hello @cristiangervasi. Unfortunately I have not been able to test on macOS because I do not have access to one. I'll see if I can find a way to test it on that OS

Thanks

**Comment by soymanuvalle** [comment]
@cristiangervasi This works on macOS, I've been using it for the last month without issues.
